### ISSUE TITLE
Dead Link in installation instructions

### ISSUE THREAD

**Issue by kanghj** [kirilluk/statechum#1]
Hello @kirilluk, 

Referring to the installation instructions, resources/introduction/index.html#installation-user, the link provided to download some zip files at http://www.dcs.shef.ac.uk/~kirill/statechum/statechum-d55bec4-bin.zip is dead. 

Can I check what is the correct url to download these files now? 

Thanks!

**Comment by kirilluk** [comment]
The correct URL is https://staffwww.dcs.shef.ac.uk/people/K.Bogdanov/statechum/statechum-d55bec4-bin.zip 
Documentation now updated - the department changed the structure of their web pages and not all links were updated to reflect this.

Thank you for the feedback.
